/**
 * icons.ts — generate the PWA app icons.
 *
 *   npm run icons
 *
 * A real icon is an exit criterion (the app has to install to an Android home
 * screen and look like an app, not a bookmark), so these are committed PNGs
 * rather than something fetched at build time. They are generated rather than
 * hand-drawn so the mark can be re-rendered at any size later, and generated by
 * a hand-rolled PNG writer rather than `sharp`/`canvas` so a 2 MB native
 * dependency does not enter a project that needs it four times, ever.
 *
 * The mark: three ascending bars on the brand green — the momentum strip of
 * DESIGN.md §2.6, which is what the whole tool is for.
 */

import { deflateSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

type RGB = [number, number, number];

const INK: RGB = [0x14, 0x16, 0x1a]; // --bg, dark theme
const ACCENT: RGB = [0x6d, 0xd3, 0x9b]; // --accent, dark theme
const DIM: RGB = [0x1f, 0x6f, 0x4a]; // --accent, light theme — the unfinished bars

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buf: Buffer): number {
  let c = 0xffffffff;
  for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Buffer): Buffer {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

/** Encode RGBA pixels as a PNG. Filter type 0 on every row — small and simple. */
function encodePng(width: number, height: number, pixels: Uint8Array): Buffer {
  const stride = width * 4;
  const raw = Buffer.alloc((stride + 1) * height);
  for (let y = 0; y < height; y++) {
    raw[y * (stride + 1)] = 0;
    Buffer.from(pixels.buffer, pixels.byteOffset + y * stride, stride).copy(raw, y * (stride + 1) + 1);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/**
 * Draw the mark.
 *
 * `padding` is the fraction of the canvas kept clear around the bars. A maskable
 * icon is cropped to a circle by Android, so it needs the safe zone the spec
 * asks for (the bars must sit inside the middle 80%); the plain icon can breathe
 * closer to the edge.
 */
function render(size: number, { maskable }: { maskable: boolean }): Uint8Array {
  const px = new Uint8Array(size * size * 4);
  const radius = maskable ? 0 : size * 0.22; // maskable icons are full-bleed
  const pad = maskable ? size * 0.26 : size * 0.2;
  const inner = size - pad * 2;

  // Three ascending bars: the last one is the one still to do.
  const gap = inner * 0.1;
  const barWidth = (inner - gap * 2) / 3;
  const heights = [0.42, 0.68, 1.0];

  const put = (x: number, y: number, [r, g, b]: RGB) => {
    const i = (y * size + x) * 4;
    px[i] = r;
    px[i + 1] = g;
    px[i + 2] = b;
    px[i + 3] = 255;
  };

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      // Rounded-square background, transparent outside the corner radius.
      if (radius > 0) {
        const dx = Math.max(radius - x, x - (size - 1 - radius), 0);
        const dy = Math.max(radius - y, y - (size - 1 - radius), 0);
        if (dx * dx + dy * dy > radius * radius) continue;
      }
      put(x, y, INK);
    }
  }

  for (let bar = 0; bar < 3; bar++) {
    const left = Math.round(pad + bar * (barWidth + gap));
    const right = Math.round(left + barWidth);
    const height = inner * heights[bar];
    const top = Math.round(pad + inner - height);
    const bottom = Math.round(pad + inner);
    const colour = bar === 2 ? DIM : ACCENT;
    for (let y = top; y < bottom; y++) {
      for (let x = left; x < right; x++) {
        if (x >= 0 && x < size && y >= 0 && y < size) put(x, y, colour);
      }
    }
  }

  return px;
}

const OUT = join(process.cwd(), 'public', 'icons');
mkdirSync(OUT, { recursive: true });

const targets: { file: string; size: number; maskable: boolean }[] = [
  { file: 'icon-192.png', size: 192, maskable: false },
  { file: 'icon-512.png', size: 512, maskable: false },
  { file: 'icon-maskable-512.png', size: 512, maskable: true },
  // iOS ignores the manifest's icons and reads this one from the <head>.
  { file: 'apple-touch-icon.png', size: 180, maskable: true },
];

for (const target of targets) {
  const png = encodePng(target.size, target.size, render(target.size, { maskable: target.maskable }));
  writeFileSync(join(OUT, target.file), png);
  console.log(`  ${target.file}  ${target.size}×${target.size}  ${(png.length / 1024).toFixed(1)} kB`);
}
console.log('\nicons written to public/icons');
