import type { DB } from '../db/index.js';
import type { NodeApp, Sample } from '../collectors/hostinger/parse.js';
import { correlate, recommend, type Account, type Deploy } from '../hosting/recommend.js';
export function HostingChart({samples,deploys,limit,now}:{samples:Sample[];deploys:Deploy[];limit:number;now:Date}) {
  const start = now.getTime()-7*86_400_000, max = Math.max(limit,...samples.map(s => Math.max(s.procs,s.threads ?? 0))) * 1.1;
  const x = (at:string) => 45 + (Date.parse(at)-start)/(7*86_400_000)*700, y = (n:number) => 210-n/max*180;
  const line = (key:'procs'|'threads') => samples.filter(s => s[key] !== null).map(s => `${x(s.at).toFixed(1)},${y(s[key]!).toFixed(1)}`).join(' ');
  const spikes = correlate(samples,deploys,limit);
  return <svg viewBox="0 0 800 250" role="img" aria-label="Seven days of hosting processes and threads" style="width:100%;max-width:1000px"><title>Processes, threads and hosting limit</title><line data-kind="limit" x1="45" x2="745" y1={y(limit)} y2={y(limit)} stroke="#dc2626" stroke-dasharray="6 4"/><text x="45" y={y(limit)-5} fill="currentColor">Limit {limit}</text>{deploys.filter(d => Date.parse(d.at) >= start && Date.parse(d.at) <= now.getTime()).map(d => <g><line data-kind="deploy" x1={x(d.at)} x2={x(d.at)} y1="25" y2="210" stroke="#999" stroke-dasharray="2 4"/><title>{d.repo} deploy {d.at}</title></g>)}<polyline data-kind="procs" points={line('procs')} fill="none" stroke="#2563eb" stroke-width="2"/><polyline data-kind="threads" points={line('threads')} fill="none" stroke="#c08700" stroke-width="2"/>{samples.map(s => <circle cx={x(s.at)} cy={y(s.procs)} r="2" fill="#2563eb"><title>{spikes.find(spike => spike.at === s.at)?.label ?? `${s.procs} processes at ${s.at}`}</title></circle>)}<text x="45" y="238" fill="currentColor">7 days ago · Blue: processes · Amber: threads · Now</text></svg>;
}
export function Hosting({db,now}:{db:DB;now:Date}) {
  const accounts = db.prepare('SELECT * FROM hosting_accounts ORDER BY label').all() as Account[];
  const samples = db.prepare('SELECT * FROM process_samples WHERE at>=? AND at<=? ORDER BY at,id').all(new Date(now.getTime()-7*86_400_000).toISOString(),now.toISOString()) as Sample[];
  return <>{!accounts.length && <p>Add a hosting account to portfolio.yaml to configure SSH or post an hPanel number.</p>}{accounts.map(account => {
    const own = samples.filter(s => s.account_id === account.id), latest = db.prepare('SELECT * FROM process_samples WHERE account_id=? ORDER BY at DESC,id DESC LIMIT 1').get(account.id) as Sample | undefined;
    const deploys = db.prepare('SELECT DISTINCT d.repo,d.at,d.sha FROM deploys d JOIN repos r ON r.name=d.repo JOIN domains h ON h.project_id=r.project_id WHERE h.hosting_account_id=? ORDER BY d.at DESC').all(account.id) as Deploy[];
    const domains = db.prepare('SELECT host FROM domains WHERE hosting_account_id=? ORDER BY host').all(account.id) as {host:string}[];
    const manual = <form method="post" action={`/hosting/${encodeURIComponent(account.id)}/manual`}><label>Processes from hPanel<input name="processes" type="number" min="0" max="1000000" step="1" required/></label><button>Save manual sample</button></form>;
    return <section class="panel"><h2>{account.label}</h2>{!account.has_ssh && <><p>SSH is not configured. Enter the process count from hPanel.</p>{manual}</>}<p>{latest ? `${latest.procs} processes; ${latest.threads ?? 'unknown'} threads; limit ${account.process_limit}; ${Math.round(Math.max(latest.procs,latest.threads ?? 0)/account.process_limit*100)}% pressure. Observed ${latest.at} (${latest.source}).` : `No samples yet. Limit ${account.process_limit}.`}</p><p>Domains: {domains.map(d => d.host).join(', ') || 'No domains assigned'}</p><HostingChart samples={own} deploys={deploys} limit={account.process_limit} now={now}/>{correlate(own,deploys,account.process_limit).map(s => <p>{s.at}: {s.label}</p>)}<table><caption>Node apps in latest sample</caption><thead><tr><th>PID</th><th>App directory</th><th>Threads</th><th>Build</th></tr></thead><tbody>{(JSON.parse(latest?.node_apps ?? '[]') as NodeApp[]).map(a => <tr><td>{a.pid}</td><td>{a.app_dir}</td><td>{a.threads}</td><td>{a.is_next_build && <strong class="signal-red">next build</strong>}</td></tr>)}</tbody></table><h3>Recommendations</h3><ul>{recommend(account,accounts,samples,now).map(r => <li>{r}</li>)}</ul><h3>Last 10 deploys</h3><ul>{deploys.slice(0,10).map(d => <li>{d.repo}: {d.at} ({d.sha.slice(0,7)})</li>)}</ul>{!!account.has_ssh && manual}</section>;
  })}</>;
}
