import type { Child } from 'hono/jsx';
import type { Freshness } from '../collectors/freshness.js';
export function FreshnessTable({ rows, timeZone }: { rows: Freshness[]; timeZone: string }) {
  const time = (at: string | null) => at ? new Intl.DateTimeFormat('en-GB', { timeZone, dateStyle: 'medium', timeStyle: 'short' }).format(new Date(at)) : 'never';
  return <table><caption>Collector freshness ({timeZone})</caption><thead><tr><th>Collector</th><th>Last success</th><th>Status</th></tr></thead><tbody>{rows.map(row => <tr><td>{row.collector}</td><td>{time(row.last_ok)}</td><td>{row.stale ? `stale since ${time(row.stale_since)}` : 'fresh'}{row.last_error && <small>Last error: {row.last_error}</small>}</td></tr>)}</tbody></table>;
}
const css = `:root{color-scheme:light dark;--bg:#f5f6f8;--card:#fff;--ink:#182232;--line:#cbd2dc;--muted:#586579}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.5 system-ui,sans-serif}header,main,footer{max-width:1500px;margin:auto;padding:20px}nav{display:flex;flex-wrap:wrap;gap:16px;align-items:center}a{color:inherit;text-underline-offset:3px}h1{font-size:1.8rem}h2{font-size:1.2rem}small{display:block;color:var(--muted);overflow-wrap:anywhere}.badge{background:#b91c1c;color:white;padding:2px 9px;border-radius:15px}.board{display:flex;gap:12px;overflow-x:auto;max-width:100%;padding-bottom:12px;align-items:flex-start}.board>section{flex:0 0 250px;min-width:0}.card{font-size:.9rem}.card details{margin-top:6px}.card summary{cursor:pointer;color:var(--muted)}.signal-red{color:#dc2626;font-weight:600}.stage-count{color:var(--muted);font-size:.9rem}.local-only{margin-top:24px}.card,section.panel{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px;margin-bottom:8px;overflow-wrap:anywhere}.dot{display:inline-block;width:11px;height:11px;border-radius:50%;margin-right:5px;background:#88909b}.green{background:#188440}.red{background:#dc2626}.amber,.pending{background:#c08700}.unknown{background:transparent;border:2px solid #88909b}.signals{display:flex;gap:12px;flex-wrap:wrap;margin:6px 0}input,button{font:inherit;padding:7px;border:1px solid var(--line);border-radius:5px;max-width:100%}input{width:100%}form{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}button{cursor:pointer}table{border-collapse:collapse;width:100%;font-size:.9rem}th,td{padding:8px;text-align:left;border-bottom:1px solid var(--line);overflow-wrap:anywhere}caption{text-align:left;color:var(--muted)}pre{white-space:pre-wrap;overflow-wrap:anywhere}footer{border-top:1px solid var(--line)}@media(prefers-color-scheme:dark){:root{--bg:#111821;--card:#1b2633;--ink:#e3e9f1;--line:#3d4b5c;--muted:#a9b7c8}}@media(max-width:699px){.board{display:block;overflow-x:visible}.board>section{width:100%}header,main,footer{padding:14px}nav{gap:12px}th,td{padding:5px}h1{font-size:1.5rem}}`;
export function Layout({ title, redCount, freshness, timeZone, children }: { title: string; redCount: number; freshness: Freshness[]; timeZone: string; children: Child }) {
  return <html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>{title} · coachme</title><style>{css}</style></head><body><header><nav aria-label="Main">{[['Today','/'],['Portfolio','/portfolio'],['Hosting','/hosting'],['Inbox','/inbox'],['Ideas','/ideas'],['Goals','/goals'],['Review','/review']].map(([name,path]) => <a href={path}>{name}</a>)}{redCount > 0 && <span class="badge" aria-label={`${redCount} open red alerts`}>{redCount}</span>}</nav></header><main><h1>{title}</h1>{children}</main><footer><FreshnessTable rows={freshness} timeZone={timeZone}/></footer></body></html>;
}
